# Generated by Django 5.0.6 on 2024-07-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='Phone_Number',
            field=models.IntegerField(),
        ),
    ]
